// <auto-generated />
using System;
using BornToMove.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BornToMove.DAL.Migrations
{
    [DbContext(typeof(MoveContext))]
    [Migration("20230711121548_RatingTable")]
    partial class RatingTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BornToMove.DAL.Move", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int?>("Rating");

                    b.Property<int?>("SweatRate");

                    b.HasKey("Id");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("BornToMove.DAL.MoveRating", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MoveId");

                    b.Property<double?>("Rating");

                    b.Property<double?>("Vote");

                    b.HasKey("Id");

                    b.HasIndex("MoveId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("BornToMove.DAL.MoveRating", b =>
                {
                    b.HasOne("BornToMove.DAL.Move", "Move")
                        .WithMany("Ratings")
                        .HasForeignKey("MoveId");
                });
#pragma warning restore 612, 618
        }
    }
}
